python prunning.py gru 10
python prunning.py gru 20
python prunning.py gru 30
python prunning.py gru 40
python prunning.py gru 50
python prunning.py gru 60
python prunning.py gru 70
python prunning.py gru 80
python prunning.py gru 90
python prunning.py lstm 10
python prunning.py lstm 20
python prunning.py lstm 30
python prunning.py lstm 40
python prunning.py lstm 50
python prunning.py lstm 60
python prunning.py lstm 70
python prunning.py lstm 80
python prunning.py lstm 90
python prunning.py rnn 10
python prunning.py rnn 20
python prunning.py rnn 30
python prunning.py rnn 40
python prunning.py rnn 50
python prunning.py rnn 60
python prunning.py rnn 70
python prunning.py rnn 80
python prunning.py rnn 90
